---
- hosts: localhost
  connection: local
  become: yes
  tasks:
#  - name: Say hi
#    tags: foo
#    shell: echo "hi"

- include: tasks/zsh.yml
- include: tasks/lvm.yml
- include: tasks/httpd01.yml
